var L=e=>{throw TypeError(e)};var N=(e,t,n)=>t.has(e)||L("Cannot "+n);var h=(e,t,n)=>(N(e,t,"read from private field"),n?n.call(e):t.get(e)),g=(e,t,n)=>t.has(e)?L("Cannot add the same private member more than once"):t instanceof WeakSet?t.add(e):t.set(e,n);import{a as M}from"./assets/vendor-CNNbG8jS.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))r(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function n(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(s){if(s.ep)return;s.ep=!0;const o=n(s);fetch(s.href,o)}})();const T=["Graham","Howell","Bauch","Lebsack","Dietrich","Schulist","Weissnat","Runolfsdottir","Reichert","DuBuque"],S=["Yahoo","Microsoft","Google","Tesla","Adobe","Foxtrot","Comfy","Feacebook","Rozetca","Adidas"],A=["Ukraine","United States","Israel","France","Germany","Türkiye","Spain","Greece","Denmark","Norway"],y=["Active","Inactive"],k=["(205)","(302)","(252)","(629)","(406)","(208)","(704)","(050)","(067)","(099)"],p=["0","1","2","3","4","5","6","7","8","9"],l=e=>{const t=Math.floor(Math.random()*S.length),n=Math.floor(Math.random()*y.length);return e===y?e[n]:e[t]},H=()=>{let e=l(T),t=l(S),n=`${l(k)} 555-${l(p)}${l(p)}${l(p)}${l(p)}`,r=l(A),s=`@${t.toLowerCase()}.com`,o=l(y);return{id:Date.now(),lastName:e,company:t,phoneNumder:n,email:s,country:r,status:o}};var m;class I{constructor(){g(this,m,8);this.KEY="42263617-81d7156b9f7b88cd7b1016c2a",this.URL="https://pixabay.com",this.resources="/api/"}async getCustomName(t){const n={key:this.KEY,safesearch:!0,per_page:h(this,m),page:t},r=`${this.URL}${this.resources}`;try{return(await M.get(r,{params:n})).data}catch(s){throw new Error(s.response.status)}}get pageSize(){return h(this,m)}}m=new WeakMap;function O(e,t){return e.map(r=>{let{id:s,user:o}=r;const{lastName:c,company:a,phoneNumder:i,email:w,country:q,status:b}=t(),B=b.toLowerCase()==="active"?"status__active":"status__inactive";return o.length>10&&(o="Bob"),`
          <li class='customer__item'>
          <span class='customer__info--name'> ${o[0].toUpperCase()}${o.slice(1)} ${c}</span>
            <span class='customer__info--company'> ${a}</span>
            <span class='customer__info--phoneNumder'> ${i}</span>
            <span class='customer__info--email'> ${o.toLowerCase()}${w}</span>
            <span class='customer__info--country'> ${q}</span>
            <span class='customer__info--status ${B}'> ${b}</span>
          </li>
      `}).join("")}function U(e){return`<p clas='pagination__text' >Showing data ${e*8-7} to ${e*8} of  504 entries</p>`}async function R(e,t){let n=[];console.log("page",e);const r=document.createElement("button");r.textContent="<",r.classList.add("prev__btn"),n.push(r);const s=document.createElement("button");s.textContent=">",s.classList.add("next__btn");let o=document.createElement("button");t-5===e?o.textContent=t-1:o.textContent="...",o.classList.add("page__btn");const c=document.createElement("button");if(c.textContent=t,c.classList.add("page__btn"),e===t)for(let a=t-5;a<=t;a++){const i=document.createElement("button");i.textContent=a,i.classList.add("page__btn"),n.push(i)}else{console.log(e,"+++");for(let a=e;a<=e+3;a++){const i=document.createElement("button");i.textContent=a,i.classList.add("page__btn"),n.push(i)}}return n.push(o,c,s),n}const C=new I;document.querySelector("body");document.querySelector(".sidebar__list");const D=document.querySelectorAll(".sidebar__btn"),$=document.querySelectorAll(".content"),v=document.querySelector(".custom__info"),f=document.querySelector(".sidebar");//!!!!!!!!!!!!!!!!!
document.querySelector(".cont__view");const x=document.querySelector(".header");document.getElementById("customers");const F=document.querySelector(".pagination__text"),E=document.querySelector(".page__buttons");document.querySelector(".prev__btn");document.querySelector(".next__btn");let u=1,d;D.forEach(e=>{e.addEventListener("click",()=>{const t=e.getAttribute("data-content");$.forEach(n=>n.classList.remove("active")),window.innerWidth<=767&&f.classList.add("display__none"),document.getElementById(t).classList.add("active"),x.classList.remove("display__none"),t==="customers"&&_(u)})});$.forEach(e=>{const t=document.createElement("button");f.classList.remove("display__none"),f.classList.add("sidebar"),t.textContent="Back",t.classList.add("back__button"),e.prepend(t),t.addEventListener("click",()=>{e.classList.remove("active"),f.classList.remove("display__none"),x.classList.add("display__none")})});async function _(e){v.innerHTML="";try{e>d&&(e=1);const t=await C.getCustomName(e);d=Math.ceil(t.totalHits/C.pageSize);const n=O(t.hits,H);v.insertAdjacentHTML("beforeend",n);const r=U(e);F.innerHTML=r,G()}catch(t){console.log(t)}finally{e+=1}}async function G(){E.innerHTML="",(await R(u,d)).forEach(t=>{t.addEventListener("click",()=>{let n=t.textContent;if(n===">")u<d-5&&(u++,_(u));else if(n==="<")u>1&&(u--,_(u));else if(n!=="..."){n===d&&(u=n),_(n);//!!!!!!!!!!!!!!!!!
}}),E.appendChild(t)})}
//# sourceMappingURL=index.js.map
